[package]
name = "data_preparation"
edition.workspace = true
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description.workspace = true

[dependencies]
tch = "0.15.0"
anyhow = "1.0"

[dev-dependencies]
criterion = "0.5"
tempfile = "3.3.0"

[[bench]]
name = "dataset_bench"
harness = false