[package]
name = "grpo_rewards"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "grpo_rewards"
crate-type = ["cdylib"]

[dependencies]
anyhow = "*"
pyo3 = { version = "0.23.3", features = ["anyhow"] }
