[package]
name = "grpo_rewards"
version = "0.1.0"
edition = "2021"

[lib]
name = "grpo_rewards"
crate-type = ["rlib","cdylib"]

[dependencies]
anyhow = "*"
pyo3 = { version = "0.23.3", features = ["anyhow"] }
libloading = "0.8"
lazy_static = "1.4"